### ISSUE TITLE
MakeFile need add `-lpthread` option

### ISSUE THREAD

**Issue by lumanyu** [hq6/ProtobufJson#1]
or else bin will not run normally. It fail to run and output likes:

> 
[libprotobuf FATAL google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
fish: Job 1, './ProtobufJson ToProto Example.…' terminated by signal SIGABRT (Abort)

g++ must adds `-lpthread ` and `-L/your/libprotobuf.so/path` to fix this issue.

**Comment by hq6** [comment]
@lumanyu Thank you for reporting this issue!

What OS and version of GCC are you running? Also, how did you install protobuf?

It looks like I am statically linking while you're trying to link dynamically.

**Comment by hq6** [comment]
I've updated the Makefile to make the options overrideable.

**Comment by hq6** [comment]
Closing this issue because of no further responses. Please reopen if the issue persists.
