### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Z-28** [hq6/ProtobufJson#2]
I have downloaded ProtobufJson, can you please explain what to do next?

I try to run

`./ProtobufJson ToProto Example.proto Example '{"x": 5, "text": "Hello World"}' > Output.bin`

but i get the error message

`bash: ./ProtobufJson: Is a directory`

How to solve this?

**Comment by hq6** [comment]
Sorry, I missed the original notification for this issue.
You need to first install Protocol Buffers, and then run `make` to build the binary.
Then run the binary rather than the project.

**Comment by hq6** [comment]
Closing this issue due to lack of response.
